version=1.0.0
group=survivalblock.train_across_time
id=train_across_time
displayName=The Train Across Time
authors=SkyNotTheLimit, The Typhothanian
contributors=
description=Hacking WATHE into 26.1.2 since 2026
license=Apache-2.0

publish.modrinth=train_across_time

org.gradle.jvmargs=-Xmx4G
org.gradle.logging.stacktrace=full
org.gradle.caching=true
org.gradle.configuration-cache=false